version: '3'
services:
  app:
      restart: always
      build: .
      volumes:
        - ./code:/home/deepsoft/code
        - ./code/logs:/home/deepsoft/code/logs
        - ./code/uploadedFiles:/home/deepsoft/code/uploadedFiles
        - ./hanlp:/home/deepsoft/.hanlp
      command: gunicorn -w 16 -k uvicorn.workers.UvicornWorker main:app -b 0.0.0.0:3000 -t 360 # uvicorn main:app --reload --host 0.0.0.0 --port 3000
      network_mode: host
